### ISSUE TITLE
"create-clang-typeinfo option" unclear in documentation

### ISSUE THREAD

**Issue by mcgov** [HexHive/HexType#3]
What is this option? It does not seem to be a valid clang option, if it is, what is the syntax? Please clarify this in the documentation.

**Comment by jys0710** [comment]
I’m sorry for the limited explanation. I updated README again (Note that during various application tests, we found in a few cases that some type information was omitted during the transition from source code to LLVM IR (which can cause false positive issue). In order to solve this issue, HexType also relies on clang level type information using “-mllvm -create-clang-typeinfo” option.). Please check it.

**Comment by mcgov** [comment]
thanks!
